services:
  hwp-rest-server:    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: HwpReader
    image: mustards94/hwp-reader:v0.1.0
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE}
    restart: unless-stopped
